"""Build the demo from directed, public OSM road edges, without straight-line shortcuts."""
import json, math, heapq
from pathlib import Path
osm=json.loads(Path('data/delhi-roads.osm.json').read_text())
nodes={e['id']:e for e in osm['elements'] if e['type']=='node'}
adj={}
def distance(a,b):
 return math.hypot((a['lat']-b['lat'])*111195,(a['lon']-b['lon'])*111195*math.cos(math.radians(a['lat'])))
for w in osm['elements']:
 t=w.get('tags',{})
 if w['type']!='way' or t.get('highway') not in ['primary','secondary','tertiary','residential','primary_link','secondary_link','tertiary_link'] or t.get('access') in ['private','no'] or t.get('motor_vehicle')=='no':continue
 for a,b in zip(w['nodes'],w['nodes'][1:]):
  length=distance(nodes[a],nodes[b]);one=t.get('oneway');name=t.get('name','Connecting road')
  if one!='-1':adj.setdefault(a,[]).append((b,length,name))
  if one=='-1' or (one not in ['yes','1','true'] and t.get('junction')!='roundabout'):adj.setdefault(b,[]).append((a,length,name))
start_nodes={n for w in osm['elements'] if w['type']=='way' and w.get('tags',{}).get('name')=='Doctor Rajendra Prasad Road' for n in w['nodes']}
start=min(start_nodes & adj.keys(),key=lambda n:nodes[n]['lon'])
end=min(adj,key=lambda n:distance(nodes[n],{'lat':28.6129,'lon':77.2295}))
queue=[(0,start)];cost={start:0};prev={}
while queue:
 d,n=heapq.heappop(queue)
 if d!=cost[n]:continue
 if n==end:break
 for to,length,name in adj.get(n,[]):
  if d+length<cost.get(to,math.inf):cost[to]=d+length;prev[to]=(n,name);heapq.heappush(queue,(d+length,to))
if end not in prev:
 end=min(cost,key=lambda n:distance(nodes[n],{'lat':28.6129,'lon':77.2295}))
assert end in prev,'No connected route in this road snapshot'
route=[end];names=[]
while route[-1]!=start:
 n,name=prev[route[-1]];route.append(n);names.append(name)
route.reverse();names.reverse()
lengths=[0]
for a,b in zip(route,route[1:]):lengths.append(lengths[-1]+distance(nodes[a],nodes[b]))
blocked=[min(range(len(route)),key=lambda i:abs(lengths[i]-lengths[-1]*fraction)) for fraction in [.4,.65]]
data={'provenance':'Directed OpenStreetMap road route; '+osm['osm3s']['timestamp_osm_base'],'nodeIds':route,'roadNames':list(dict.fromkeys(names)),'keyWaypoints':[[nodes[n]['lat'],nodes[n]['lon']] for n in route],'gnssBlockedStartIdx':blocked[0],'gnssBlockedEndIdx':blocked[1],'interpolationDensity':1}
Path('js/demo-route.js').write_text('/* NavDR road-following scenario. Generated by tools/build_demo_route.py; OSM attribution in data/README.md. */\nObject.assign(NavDR.RouteData, '+json.dumps(data,indent=2)+');\n')
print(f'{len(route)} connected road nodes, {lengths[-1]:.0f} m: '+', '.join(data['roadNames']))
